// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using MusicHall.Data;

namespace MusicHall.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190501194435_Messages")]
    partial class Messages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MusicHall.Core.Domain.Administrators.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .HasColumnName("disabled");

                    b.Property<string>("Email")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name");

                    b.Property<Guid>("Guid")
                        .HasColumnName("guid");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .HasColumnName("login");

                    b.Property<string>("PasswordRecoveryToken")
                        .HasColumnName("password_recovery_token");

                    b.Property<DateTime?>("PasswordRecoveryTokenDateGenerated")
                        .HasColumnName("password_recovery_token_date_generated");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("administrators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disabled = false,
                            Email = "admin@admin.fr",
                            FirstName = "admin",
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastName = "admin",
                            Login = "admin@admin.fr",
                            UpdatedAtOnUtc = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Administrators.AdministratorPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("AdministratorId")
                        .HasColumnName("administrator_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at");

                    b.Property<string>("Password")
                        .HasColumnName("password");

                    b.Property<int>("PasswordFormat")
                        .HasColumnName("password_format");

                    b.Property<int>("PasswordFormatId")
                        .HasColumnName("password_format_id");

                    b.Property<string>("PasswordSalt")
                        .HasColumnName("password_salt");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.ToTable("administrator_passwords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdministratorId = 1,
                            CreatedAtUtc = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "admin",
                            PasswordFormat = 0,
                            PasswordFormatId = 0,
                            UpdatedAtOnUtc = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Common.Civility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("civilities");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Messages.EmailAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnName("email");

                    b.Property<bool>("EnableSsl")
                        .HasColumnName("enable_ssl");

                    b.Property<string>("Host")
                        .HasColumnName("host");

                    b.Property<string>("Password")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnName("port");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseDefaultCredentials")
                        .HasColumnName("use_default_credentials");

                    b.Property<string>("Username")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("email_account");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Messages.MessageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("AttachedDownloadId")
                        .HasColumnName("attached_download_id");

                    b.Property<string>("BccEmailAddresses")
                        .HasColumnName("bcc_email_addresses");

                    b.Property<string>("Body")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at");

                    b.Property<int?>("DelayBeforeSend")
                        .HasColumnName("delay_before_send");

                    b.Property<int>("DelayPeriod");

                    b.Property<int>("DelayPeriodId")
                        .HasColumnName("delay_period_id");

                    b.Property<int>("EmailAccountId")
                        .HasColumnName("email_account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("Subject")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("message_template");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Messages.QueuedEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("AttachedDownloadId")
                        .HasColumnName("attachment_download_id");

                    b.Property<string>("AttachmentFileName")
                        .HasColumnName("attachment_file_name");

                    b.Property<string>("AttachmentFilePath")
                        .HasColumnName("attachment_file_path");

                    b.Property<string>("Bcc")
                        .HasColumnName("bcc");

                    b.Property<string>("Body")
                        .HasColumnName("body");

                    b.Property<string>("CC")
                        .HasColumnName("cc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("DontSendBeforeDateUtc")
                        .HasColumnName("dont_send_before_date_utc");

                    b.Property<int>("EmailAccountId")
                        .HasColumnName("email_account_id");

                    b.Property<string>("From")
                        .HasColumnName("from");

                    b.Property<string>("FromName")
                        .HasColumnName("from_name");

                    b.Property<int>("Priority");

                    b.Property<int>("PriorityId")
                        .HasColumnName("priority_id");

                    b.Property<string>("ReplyTo")
                        .HasColumnName("reply_to");

                    b.Property<string>("ReplyToName")
                        .HasColumnName("reply_to_name");

                    b.Property<DateTime?>("SentOnUtc")
                        .HasColumnName("sent_on_utc");

                    b.Property<int>("SentTries")
                        .HasColumnName("sent_tries");

                    b.Property<string>("Subject")
                        .HasColumnName("subject");

                    b.Property<string>("To")
                        .HasColumnName("to");

                    b.Property<string>("ToName")
                        .HasColumnName("to_name");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmailAccountId");

                    b.ToTable("queued_email");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("CivilityId")
                        .HasColumnName("civility_id");

                    b.Property<bool>("Confirmed")
                        .HasColumnName("confirmed");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .HasColumnName("disabled");

                    b.Property<string>("Email")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name");

                    b.Property<Guid>("Guid")
                        .HasColumnName("guid");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name");

                    b.Property<string>("Mobile")
                        .HasColumnName("mobile");

                    b.Property<string>("PasswordRecoveryToken")
                        .HasColumnName("password_recovery_token");

                    b.Property<DateTime?>("PasswordRecoveryTokenDateGenerated")
                        .HasColumnName("password_recovery_token_date_generated");

                    b.Property<string>("Phone")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CivilityId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Users.UserPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at");

                    b.Property<string>("Password")
                        .HasColumnName("password");

                    b.Property<int>("PasswordFormat")
                        .HasColumnName("password_format");

                    b.Property<int>("PasswordFormatId")
                        .HasColumnName("password_format_id");

                    b.Property<string>("PasswordSalt")
                        .HasColumnName("password_salt");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_passwords");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Administrators.AdministratorPassword", b =>
                {
                    b.HasOne("MusicHall.Core.Domain.Administrators.Administrator", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Messages.QueuedEmail", b =>
                {
                    b.HasOne("MusicHall.Core.Domain.Messages.EmailAccount", "EmailAccount")
                        .WithMany()
                        .HasForeignKey("EmailAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Users.User", b =>
                {
                    b.HasOne("MusicHall.Core.Domain.Common.Civility", "Civility")
                        .WithMany()
                        .HasForeignKey("CivilityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Users.UserPassword", b =>
                {
                    b.HasOne("MusicHall.Core.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
