// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using MusicHall.Data;

namespace MusicHall.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210318084147_UpdateIdentityColumns")]
    partial class UpdateIdentityColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MusicHall.Core.Domain.Administrators.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Disabled")
                        .HasColumnName("disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name")
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnName("guid")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .HasColumnName("login")
                        .HasColumnType("text");

                    b.Property<string>("PasswordRecoveryToken")
                        .HasColumnName("password_recovery_token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordRecoveryTokenDateGenerated")
                        .HasColumnName("password_recovery_token_date_generated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("administrators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disabled = false,
                            Email = "admin@admin.fr",
                            FirstName = "admin",
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastName = "admin",
                            Login = "admin@admin.fr",
                            UpdatedAtOnUtc = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Administrators.AdministratorPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AdministratorId")
                        .HasColumnName("administrator_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("text");

                    b.Property<int>("PasswordFormat")
                        .HasColumnName("password_format")
                        .HasColumnType("integer");

                    b.Property<int>("PasswordFormatId")
                        .HasColumnName("password_format_id")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordSalt")
                        .HasColumnName("password_salt")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.ToTable("administrator_passwords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdministratorId = 1,
                            CreatedAtUtc = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "admin",
                            PasswordFormat = 0,
                            PasswordFormatId = 0,
                            UpdatedAtOnUtc = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Common.Civility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("civilities");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Messages.EmailAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnName("display_name")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<bool>("EnableSsl")
                        .HasColumnName("enable_ssl")
                        .HasColumnType("boolean");

                    b.Property<string>("Host")
                        .HasColumnName("host")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnName("port")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("UseDefaultCredentials")
                        .HasColumnName("use_default_credentials")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .HasColumnName("user_name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("email_account");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Messages.MessageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AttachedDownloadId")
                        .HasColumnName("attached_download_id")
                        .HasColumnType("integer");

                    b.Property<string>("BccEmailAddresses")
                        .HasColumnName("bcc_email_addresses")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnName("body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DelayBeforeSend")
                        .HasColumnName("delay_before_send")
                        .HasColumnType("integer");

                    b.Property<int>("DelayPeriod")
                        .HasColumnType("integer");

                    b.Property<int>("DelayPeriodId")
                        .HasColumnName("delay_period_id")
                        .HasColumnType("integer");

                    b.Property<int>("EmailAccountId")
                        .HasColumnName("email_account_id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnName("subject")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("message_template");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Messages.QueuedEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AttachedDownloadId")
                        .HasColumnName("attachment_download_id")
                        .HasColumnType("integer");

                    b.Property<string>("AttachmentFileName")
                        .HasColumnName("attachment_file_name")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentFilePath")
                        .HasColumnName("attachment_file_path")
                        .HasColumnType("text");

                    b.Property<string>("Bcc")
                        .HasColumnName("bcc")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnName("body")
                        .HasColumnType("text");

                    b.Property<string>("CC")
                        .HasColumnName("cc")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnName("created_on_utc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DontSendBeforeDateUtc")
                        .HasColumnName("dont_send_before_date_utc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EmailAccountId")
                        .HasColumnName("email_account_id")
                        .HasColumnType("integer");

                    b.Property<string>("From")
                        .HasColumnName("from")
                        .HasColumnType("text");

                    b.Property<string>("FromName")
                        .HasColumnName("from_name")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("PriorityId")
                        .HasColumnName("priority_id")
                        .HasColumnType("integer");

                    b.Property<string>("ReplyTo")
                        .HasColumnName("reply_to")
                        .HasColumnType("text");

                    b.Property<string>("ReplyToName")
                        .HasColumnName("reply_to_name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentOnUtc")
                        .HasColumnName("sent_on_utc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SentTries")
                        .HasColumnName("sent_tries")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasColumnName("subject")
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .HasColumnName("to")
                        .HasColumnType("text");

                    b.Property<string>("ToName")
                        .HasColumnName("to_name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailAccountId");

                    b.ToTable("queued_email");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CivilityId")
                        .HasColumnName("civility_id")
                        .HasColumnType("integer");

                    b.Property<bool>("Confirmed")
                        .HasColumnName("confirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Disabled")
                        .HasColumnName("disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name")
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnName("guid")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnName("mobile")
                        .HasColumnType("text");

                    b.Property<string>("PasswordRecoveryToken")
                        .HasColumnName("password_recovery_token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordRecoveryTokenDateGenerated")
                        .HasColumnName("password_recovery_token_date_generated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CivilityId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Users.UserPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("text");

                    b.Property<int>("PasswordFormat")
                        .HasColumnName("password_format")
                        .HasColumnType("integer");

                    b.Property<int>("PasswordFormatId")
                        .HasColumnName("password_format_id")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordSalt")
                        .HasColumnName("password_salt")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtOnUtc")
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_passwords");
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Administrators.AdministratorPassword", b =>
                {
                    b.HasOne("MusicHall.Core.Domain.Administrators.Administrator", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Messages.QueuedEmail", b =>
                {
                    b.HasOne("MusicHall.Core.Domain.Messages.EmailAccount", "EmailAccount")
                        .WithMany()
                        .HasForeignKey("EmailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Users.User", b =>
                {
                    b.HasOne("MusicHall.Core.Domain.Common.Civility", "Civility")
                        .WithMany()
                        .HasForeignKey("CivilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicHall.Core.Domain.Users.UserPassword", b =>
                {
                    b.HasOne("MusicHall.Core.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
